// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msg_id.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol.MessageHeader {

  /// <summary>Holder for reflection information generated from msg_id.proto</summary>
  public static partial class MsgIdReflection {

    #region Descriptor
    /// <summary>File descriptor for msg_id.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxtc2dfaWQucHJvdG8SEFBiLk1lc3NhZ2VIZWFkZXIiOAoNTWVzc2FnZUhl",
            "YWRlchITCgttc2dfdmVyc2lvbhgBIAEoDRISCgpzZXFfTnVtYmVyGAIgASgN",
            "IoABChRNZXNzYWdlSGVhZGVyTmV0d29yaxIzCgZtc2dfaWQYASABKA4yIy5Q",
            "Yi5NZXNzYWdlSGVhZGVyLmVOZXR3b3JrTWVzc2FnZUlkEjMKCm1zZ19oZWFk",
            "ZXIYAiABKAsyHy5QYi5NZXNzYWdlSGVhZGVyLk1lc3NhZ2VIZWFkZXIqRAoR",
            "ZU5ldHdvcmtNZXNzYWdlSWQSEwoPVU5LTk9XTl9NRVNTQUdFEAASGgoWTk9U",
            "SUZZX1NFU1NJT05fQ09OTkVDVBABQimqAiZHb29nbGUuUHJvdG9idWYuUHJv",
            "dG9jb2wuTWVzc2FnZUhlYWRlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Protocol.MessageHeader.MessageHeader), global::Google.Protobuf.Protocol.MessageHeader.MessageHeader.Parser, new[]{ "MsgVersion", "SeqNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Protocol.MessageHeader.MessageHeaderNetwork), global::Google.Protobuf.Protocol.MessageHeader.MessageHeaderNetwork.Parser, new[]{ "MsgId", "MsgHeader" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 패킷 메시지 아이디 [네트워크 관련, 추후 인증, 로직, 길드 등 추가]
  /// enum의 경우 e접두어를 붙이고 항목은 대문자로 _를 통해 단어를 구분하여 적는다
  /// </summary>
  public enum eNetworkMessageId {
    [pbr::OriginalName("UNKNOWN_MESSAGE")] UnknownMessage = 0,
    [pbr::OriginalName("NOTIFY_SESSION_CONNECT")] NotifySessionConnect = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 메시지 항목의 변수명은 소문자를 사용하고 _를 통해 단어를 구분한다
  /// proto3의 경우 default 값을 지정해줄 수 없다
  /// 패킷 메시지 공통 헤더항목을 추가 
  /// </summary>
  public sealed partial class MessageHeader : pb::IMessage<MessageHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageHeader> _parser = new pb::MessageParser<MessageHeader>(() => new MessageHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.Protocol.MessageHeader.MsgIdReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageHeader(MessageHeader other) : this() {
      msgVersion_ = other.msgVersion_;
      seqNumber_ = other.seqNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageHeader Clone() {
      return new MessageHeader(this);
    }

    /// <summary>Field number for the "msg_version" field.</summary>
    public const int MsgVersionFieldNumber = 1;
    private uint msgVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MsgVersion {
      get { return msgVersion_; }
      set {
        msgVersion_ = value;
      }
    }

    /// <summary>Field number for the "seq_Number" field.</summary>
    public const int SeqNumberFieldNumber = 2;
    private uint seqNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SeqNumber {
      get { return seqNumber_; }
      set {
        seqNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgVersion != other.MsgVersion) return false;
      if (SeqNumber != other.SeqNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgVersion != 0) hash ^= MsgVersion.GetHashCode();
      if (SeqNumber != 0) hash ^= SeqNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MsgVersion);
      }
      if (SeqNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SeqNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MsgVersion);
      }
      if (SeqNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SeqNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgVersion);
      }
      if (SeqNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SeqNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageHeader other) {
      if (other == null) {
        return;
      }
      if (other.MsgVersion != 0) {
        MsgVersion = other.MsgVersion;
      }
      if (other.SeqNumber != 0) {
        SeqNumber = other.SeqNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            SeqNumber = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            SeqNumber = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MessageHeaderNetwork : pb::IMessage<MessageHeaderNetwork>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageHeaderNetwork> _parser = new pb::MessageParser<MessageHeaderNetwork>(() => new MessageHeaderNetwork());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageHeaderNetwork> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.Protocol.MessageHeader.MsgIdReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageHeaderNetwork() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageHeaderNetwork(MessageHeaderNetwork other) : this() {
      msgId_ = other.msgId_;
      msgHeader_ = other.msgHeader_ != null ? other.msgHeader_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageHeaderNetwork Clone() {
      return new MessageHeaderNetwork(this);
    }

    /// <summary>Field number for the "msg_id" field.</summary>
    public const int MsgIdFieldNumber = 1;
    private global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId msgId_ = global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId.UnknownMessage;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId MsgId {
      get { return msgId_; }
      set {
        msgId_ = value;
      }
    }

    /// <summary>Field number for the "msg_header" field.</summary>
    public const int MsgHeaderFieldNumber = 2;
    private global::Google.Protobuf.Protocol.MessageHeader.MessageHeader msgHeader_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.Protocol.MessageHeader.MessageHeader MsgHeader {
      get { return msgHeader_; }
      set {
        msgHeader_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageHeaderNetwork);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageHeaderNetwork other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgId != other.MsgId) return false;
      if (!object.Equals(MsgHeader, other.MsgHeader)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgId != global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId.UnknownMessage) hash ^= MsgId.GetHashCode();
      if (msgHeader_ != null) hash ^= MsgHeader.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgId != global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId.UnknownMessage) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgId);
      }
      if (msgHeader_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MsgHeader);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgId != global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId.UnknownMessage) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgId);
      }
      if (msgHeader_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MsgHeader);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgId != global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId.UnknownMessage) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgId);
      }
      if (msgHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MsgHeader);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageHeaderNetwork other) {
      if (other == null) {
        return;
      }
      if (other.MsgId != global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId.UnknownMessage) {
        MsgId = other.MsgId;
      }
      if (other.msgHeader_ != null) {
        if (msgHeader_ == null) {
          MsgHeader = new global::Google.Protobuf.Protocol.MessageHeader.MessageHeader();
        }
        MsgHeader.MergeFrom(other.MsgHeader);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgId = (global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId) input.ReadEnum();
            break;
          }
          case 18: {
            if (msgHeader_ == null) {
              MsgHeader = new global::Google.Protobuf.Protocol.MessageHeader.MessageHeader();
            }
            input.ReadMessage(MsgHeader);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgId = (global::Google.Protobuf.Protocol.MessageHeader.eNetworkMessageId) input.ReadEnum();
            break;
          }
          case 18: {
            if (msgHeader_ == null) {
              MsgHeader = new global::Google.Protobuf.Protocol.MessageHeader.MessageHeader();
            }
            input.ReadMessage(MsgHeader);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
